name: Daily Check-in
on:
  schedule:
    - cron: '0 0 * * *'  # 在每天的UTC时间 00:00 运行，你可以根据需要进行调整

jobs:
  check_in:
    name: Check-in
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 在这里添加运行签到的命令或脚本
      # 比如运行一个Python脚本的示例：
      - name: Run Check-in
        run: python main.py

      # 在这里添加发送到Server酱的命令或脚本
      # 比如发送一个HTTP POST请求的示例：
      - name: Send Notification to Server酱
        run: |
          curl -X POST -d "text=Daily Check-in completed" https://sctapi.ftqq.com/YOUR_SERVER_CHAN_SCKEY.send
